<script type="text/javascript">
$$('.btn-cart').each(function (element) {
    element.observe('click', function (event) {
        var onclick = $(this).readAttribute('onclick');
        if (onclick !== null) {
          var productId = onclick.match(/\/product\/(\d+)\/?/);
          if (productId == null) {
            var form = $(this).closest('form');
            if (form != null) {
              onclick = form.readAttribute('action');
              productId = onclick.match(/\/product\/(\d+)\/?/);
            }
          }
          if (productId) {
            productId = parseInt(productId[1]);
            try {
              rrApi.addToBasket(productId);
            } catch (e) {
            }
          }
        }
    });
});
</script>