<script type="text/javascript">
var rrPartnerId = "<?php echo Mage::getStoreConfig('vs7_retailrocket/general/partner_id'); ?>";
var rrApi = {};
var rrApiOnReady = rrApiOnReady || [];
rrApi.addToBasket = rrApi.order = rrApi.categoryView = rrApi.view =
    rrApi.recomMouseDown = rrApi.recomAddToCart = function() {};
(function(d) {
    var ref = d.getElementsByTagName('script')[0];
    var apiJs, apiJsId = 'rrApi-jssdk';
    if (d.getElementById(apiJsId)) return;
    apiJs = d.createElement('script');
    apiJs.id = apiJsId;
    apiJs.async = true;
    apiJs.src = "//cdn.retailrocket.ru/content/javascript/tracking.js";
    ref.parentNode.insertBefore(apiJs, ref);
}(document));
</script>
<div data-retailrocket-markup-block="<?php echo Mage::getStoreConfig('vs7_retailrocket/general/block_id'); ?>"></div>